# Generated by Django 5.2.3 on 2025-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_pedido_fecha_alquiler_reservaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ubicacion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
